image: debian:stable

before_script:
  - apt-get update -qq
  - apt-get install -y -qq build-essential autoconf autoconf-archive automake libcups2-dev libcupsimage2-dev
  - autoreconf --install --verbose --force
  - ./configure

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make

tarball:
  stage: deploy
  only:
    - tags
    - master
  script:
    - make dist
  artifacts:
    name: "tarball"
    paths:
      - "*.tar.gz"
